---
title: "Case study"
author: "Te-Hsuan Huang"
date: "2025-10-19"
output: html_document
---

* if you want to a map being interactive, you should html, rather github

Dataset and library

```{r}
library(tidyverse)
library(leaflet)
library(p8105.datasets)

data(nyc_airbnb)
```

Price

```{r}
nyc_airbnb |> 
  drop_na(price) |> 
  group_by(neighbourhood_group) |> 
  summarize(
    mean_price=mean(price),
    min_price=min(price),
    max_price=max(price)
  )
```

what a room type in a given neighborhood.

```{r}
nyc_airbnb |> 
  drop_na(price) |> 
  filter(neighbourhood_group=="Manhattan") |> 
  group_by(room_type) |> 
  summarize(
    mean_price=mean(price),
    min_price=min(price),
    max_price=max(price)
  )
```

Not specific region

```{r}
nyc_airbnb |> 
  drop_na(price) |> 
  group_by(room_type, neighbourhood_group) |> 
  summarize(
    mean_price=mean(price),
    min_price=min(price),
    max_price=max(price)
  )
```

Making a table

```{r}
nyc_airbnb |> 
  drop_na(price) |> 
  group_by(room_type, neighbourhood_group) |> 
  summarize(
    mean_price=mean(price),
  ) |> 
  pivot_wider(
    names_from = room_type,
    values_from = mean_price
  )
```

Making a plot

```{r}
nyc_airbnb |> 
  ggplot(aes(x=price))+
  geom_histogram()+
  facet_grid(room_type ~ neighbourhood_group)+
  scale_x_continuous(limits = c(0,1000))
```

Counting

```{r}
nyc_airbnb |> 
  count(neighbourhood_group, room_type)
```

Distribution

```{r}
nyc_airbnb |> 
  filter(neighbourhood_group=="Manhattan",price<500, room_type=="Entire home/apt") |> 
  mutate(neighbourhood=fct_reorder(neighbourhood,price)) |> 
  ggplot(aes(x=neighbourhood, y=price))+
  geom_violin()+
  theme(axis.text.x = element_text(angle = 90, hjust=1, vjust = 0.5))
```

Look at extreme values

```{r}
nyc_airbnb |> 
  filter(price>9000)
```

```{r}
nyc_airbnb |> 
  filter(calculated_host_listings_count>30)
```

keep looking at location

```{r}
nyc_airbnb |> 
    filter(neighbourhood_group=="Manhattan",price<1000, room_type=="Entire home/apt") |> 
  ggplot(aes(x=lat, y=long, color=review_scores_location))+
  geom_point()

```

Can make a better map

```{r}
pal <- colorNumeric(
  palette = "viridis",
  domain=nyc_airbnb$price
)

nyc_airbnb |> 
    filter(neighbourhood_group=="Manhattan",price<1000, room_type=="Entire home/apt") |> 
  sample_n(100) |> 
  leaflet() |> 
  addTiles() |> 
  addCircleMarkers(~long,~lat,radius=2, color = ~pal(price))
```

